<?php
declare(strict_types=1);

namespace TypeDock\Install;

use DateTimeImmutable;
use PDO;
use Phinx\Config\Config as PhinxConfig;
use Phinx\Migration\Manager as PhinxManager;
use Ramsey\Uuid\Uuid;
use RuntimeException;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Output\BufferedOutput;

/**
 * Shared installation logic used by both the CLI and the browser wizard.
 *
 * Safe to call individual steps independently; callers decide ordering.
 */
final class Installer
{
    public const LOCK_FILE      = '/storage/.installed';
    public const PROGRESS_FILE  = '/storage/.installing';

    public function __construct(private string $root)
    {
    }

    public static function isInstalled(string $root): bool
    {
        return is_file($root . self::LOCK_FILE);
    }

    /**
     * @return array{php:bool,extensions:array<string,bool>,optional:array<string,bool>,writable:array<string,bool>,mod_rewrite:bool|null}
     */
    public function checkEnvironment(): array
    {
        $required = ['pdo', 'mbstring', 'json', 'openssl', 'fileinfo'];
        $optional = ['gd', 'intl', 'pdo_mysql', 'pdo_pgsql', 'pdo_sqlite'];

        $ext = [];
        foreach ($required as $e) {
            $ext[$e] = extension_loaded($e);
        }
        $opt = [];
        foreach ($optional as $e) {
            $opt[$e] = extension_loaded($e);
        }

        $writable = [
            'storage'          => is_writable($this->root . '/storage'),
            'storage/cache'    => is_writable($this->root . '/storage/cache'),
            'storage/logs'     => is_writable($this->root . '/storage/logs'),
            'storage/sessions' => is_writable($this->root . '/storage/sessions'),
            'storage/uploads'  => is_writable($this->root . '/storage/uploads'),
            'root (for .env)'  => is_writable($this->root),
        ];

        $rewrite = null;
        if (function_exists('apache_get_modules')) {
            $rewrite = in_array('mod_rewrite', apache_get_modules(), true);
        }

        return [
            'php'         => PHP_VERSION_ID >= 80200,
            'extensions'  => $ext,
            'optional'    => $opt,
            'writable'    => $writable,
            'mod_rewrite' => $rewrite,
        ];
    }

    /**
     * Test a DB connection with the given config. Returns null on success, message on failure.
     *
     * @param array{driver:string,host?:string,port?:int|string,database?:string,username?:string,password?:string,sqlite_path?:string,charset?:string} $db
     */
    public function testDatabase(array $db): ?string
    {
        try {
            $this->makePdo($db);
            return null;
        } catch (\Throwable $e) {
            return $e->getMessage();
        }
    }

    /**
     * Write config.php from the given values, merged on top of config.php.example defaults.
     *
     * The output is valid PHP ("return [...];"), produced via var_export for each value
     * — never string interpolation — so user-supplied values cannot inject code.
     *
     * @param array<string,string> $values
     */
    public function writeConfig(array $values): void
    {
        $values['APP_KEY']        = ($values['APP_KEY']        ?? '') ?: self::generateKey();
        $values['SESSION_SECRET'] = ($values['SESSION_SECRET'] ?? '') ?: self::generateKey();

        $defaults = [];
        $template = $this->root . '/config.php.example';
        if (is_file($template)) {
            $loaded = require $template;
            if (is_array($loaded)) {
                $defaults = $loaded;
            }
        }

        $final = $defaults;
        foreach ($values as $k => $v) {
            $final[$k] = (string) $v;
        }

        $lines = [
            '<?php',
            '/**',
            ' * TypeDock configuration.',
            ' * Generated by the installer on ' . gmdate('c') . '.',
            ' *',
            ' * Real environment variables override any value here. Edit this file to change',
            ' * runtime configuration on shared hosting; rotate APP_KEY and SESSION_SECRET if',
            ' * ever exposed.',
            ' */',
            '',
            'declare(strict_types=1);',
            '',
            'return [',
        ];
        foreach ($final as $k => $v) {
            if (!is_string($k)) {
                continue;
            }
            $lines[] = sprintf('    %s => %s,', var_export($k, true), var_export((string) $v, true));
        }
        $lines[] = '];';
        $lines[] = '';

        $path = $this->root . '/config.php';
        if (file_put_contents($path, implode("\n", $lines), LOCK_EX) === false) {
            throw new RuntimeException('Failed to write ' . $path);
        }
        @chmod($path, 0600);
    }

    /**
     * Run all pending Phinx migrations via the PHP API (no shell).
     */
    public function runMigrations(): void
    {
        $configArr = require $this->root . '/phinx.php';
        $config    = new PhinxConfig($configArr, $this->root . '/phinx.php');
        $manager   = new PhinxManager($config, new StringInput(''), new BufferedOutput());
        $manager->migrate('default');
    }

    /**
     * Insert the initial admin user.
     *
     * @param array{driver:string,host?:string,port?:int|string,database?:string,username?:string,password?:string,sqlite_path?:string,charset?:string} $db
     */
    public function createAdmin(array $db, string $email, string $name, string $password): string
    {
        if ($email === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
            throw new RuntimeException('A valid email address is required.');
        }
        if (strlen($password) < 12) {
            throw new RuntimeException('Password must be at least 12 characters.');
        }

        $pdo  = $this->makePdo($db);
        $id   = Uuid::uuid7()->toString();
        $hash = password_hash($password, PASSWORD_BCRYPT);
        $now  = (new DateTimeImmutable())->format('Y-m-d H:i:s');

        $pdo->prepare(
            'INSERT INTO users (id, email, password_hash, name, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)'
        )->execute([$id, $email, $hash, $name !== '' ? $name : $email, 'admin', $now, $now]);

        return $id;
    }

    public function lock(string $version): void
    {
        $payload = json_encode([
            'version'      => $version,
            'installed_at' => gmdate('c'),
        ], JSON_UNESCAPED_SLASHES);
        file_put_contents($this->root . self::LOCK_FILE, (string) $payload, LOCK_EX);
        @unlink($this->root . self::PROGRESS_FILE);
    }

    public function beginProgress(): void
    {
        $path = $this->root . self::PROGRESS_FILE;
        if (is_file($path) && (time() - filemtime($path)) < 600) {
            throw new RuntimeException('Installation is already running.');
        }
        file_put_contents($path, (string) time(), LOCK_EX);
    }

    public function endProgress(): void
    {
        @unlink($this->root . self::PROGRESS_FILE);
    }

    public static function generateKey(): string
    {
        return 'base64:' . base64_encode(random_bytes(32));
    }

    /**
     * @param array<string,mixed> $db
     */
    private function makePdo(array $db): PDO
    {
        $driver  = $db['driver'] ?? 'mysql';
        $charset = $db['charset'] ?? 'utf8mb4';

        $dsn = match ($driver) {
            'sqlite' => 'sqlite:' . ($db['sqlite_path'] ?? $this->root . '/storage/database.sqlite'),
            'pgsql'  => sprintf('pgsql:host=%s;port=%d;dbname=%s', $db['host'] ?? '127.0.0.1', (int) ($db['port'] ?? 5432), $db['database'] ?? ''),
            default  => sprintf('mysql:host=%s;port=%d;dbname=%s;charset=%s', $db['host'] ?? '127.0.0.1', (int) ($db['port'] ?? 3306), $db['database'] ?? '', $charset),
        };

        return new PDO(
            $dsn,
            $driver === 'sqlite' ? null : ($db['username'] ?? ''),
            $driver === 'sqlite' ? null : ($db['password'] ?? ''),
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
    }

}
