<?php
declare(strict_types=1);

namespace TypeDock\Content;

/**
 * Render Tiptap / ProseMirror JSON into a Markdown projection.
 *
 * The JSON document remains canonical. This projection is generated by core
 * for lightweight search, exports, and crawler-friendly `.md` responses.
 */
class TiptapMarkdownRenderer
{
    /**
     * @param  string|array<string, mixed>|null $doc
     */
    public static function render(string|array|null $doc): string
    {
        if ($doc === null || $doc === '') {
            return '';
        }
        if (is_string($doc)) {
            $decoded = json_decode($doc, true);
            if (!is_array($decoded)) {
                return '';
            }
            $doc = $decoded;
        }
        if (($doc['type'] ?? '') !== 'doc') {
            return '';
        }

        return trim(self::renderBlocks($doc['content'] ?? []));
    }

    /**
     * @param array<int, mixed> $nodes
     */
    private static function renderBlocks(array $nodes): string
    {
        $blocks = [];
        foreach ($nodes as $node) {
            if (!is_array($node)) {
                continue;
            }
            $block = self::renderBlock($node);
            if ($block !== '') {
                $blocks[] = $block;
            }
        }
        return implode("\n\n", $blocks);
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function renderBlock(array $node): string
    {
        $type = (string) ($node['type'] ?? '');
        return match ($type) {
            'heading'        => self::heading($node),
            'paragraph'      => self::inline($node['content'] ?? []),
            'bulletList'     => self::list($node['content'] ?? [], false),
            'orderedList'    => self::list($node['content'] ?? [], true),
            'listItem'       => self::renderBlocks($node['content'] ?? []),
            'blockquote'     => self::blockquote($node),
            'codeBlock'      => self::codeBlock($node),
            'horizontalRule' => '---',
            'image'          => self::image($node),
            'bookmark'       => self::bookmark($node),
            'embed'          => self::embed($node),
            'componentBlock' => self::component($node),
            default          => self::renderBlocks($node['content'] ?? []),
        };
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function heading(array $node): string
    {
        $level = (int) ($node['attrs']['level'] ?? 2);
        if ($level < 1 || $level > 6) {
            $level = 2;
        }
        $text = self::inline($node['content'] ?? []);
        return $text === '' ? '' : str_repeat('#', $level) . ' ' . $text;
    }

    /**
     * @param array<int, mixed> $items
     */
    private static function list(array $items, bool $ordered): string
    {
        $lines = [];
        $index = 1;
        foreach ($items as $item) {
            if (!is_array($item)) {
                continue;
            }
            $content = trim(self::renderBlocks($item['content'] ?? []));
            if ($content === '') {
                continue;
            }
            $marker = $ordered ? ($index . '. ') : '- ';
            $parts  = preg_split('/\R/u', $content) ?: [];
            foreach ($parts as $lineIndex => $line) {
                $lines[] = ($lineIndex === 0 ? $marker : '  ') . $line;
            }
            $index++;
        }
        return implode("\n", $lines);
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function blockquote(array $node): string
    {
        $inner = self::renderBlocks($node['content'] ?? []);
        if ($inner === '') {
            return '';
        }
        return implode("\n", array_map(
            static fn (string $line): string => $line === '' ? '>' : '> ' . $line,
            preg_split('/\R/u', $inner) ?: []
        ));
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function codeBlock(array $node): string
    {
        $lang = preg_replace('/[^A-Za-z0-9_-]/', '', (string) ($node['attrs']['language'] ?? '')) ?? '';
        $code = self::textContent($node);
        $fence = self::fenceFor($code);
        return $fence . $lang . "\n" . $code . "\n" . $fence;
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function image(array $node): string
    {
        $attrs = $node['attrs'] ?? [];
        $src   = (string) ($attrs['src'] ?? '');
        if ($src === '') {
            return '';
        }
        $alt     = self::escapeLinkText((string) ($attrs['alt'] ?? ''));
        $caption = trim((string) ($attrs['caption'] ?? ''));
        $out     = '![' . $alt . '](' . self::escapeUrl($src) . ')';
        if ($caption !== '') {
            $out .= "\n\n_" . self::escapeText($caption) . '_';
        }
        return $out;
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function bookmark(array $node): string
    {
        $attrs = $node['attrs'] ?? [];
        $url   = (string) ($attrs['url'] ?? '');
        if ($url === '') {
            return '';
        }
        $title = trim((string) ($attrs['title'] ?? '')) ?: $url;
        $desc  = trim((string) ($attrs['description'] ?? ''));
        $out   = '[' . self::escapeLinkText($title) . '](' . self::escapeUrl($url) . ')';
        if ($desc !== '') {
            $out .= "\n\n> " . self::escapeText($desc);
        }
        return $out;
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function embed(array $node): string
    {
        $url = (string) ($node['attrs']['url'] ?? '');
        return $url === '' ? '' : '[' . self::escapeLinkText($url) . '](' . self::escapeUrl($url) . ')';
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function component(array $node): string
    {
        $attrs  = $node['attrs'] ?? [];
        $type   = trim((string) ($attrs['component'] ?? ''));
        $params = $attrs['params'] ?? [];
        if ($type === '') {
            return '';
        }
        $json = is_array($params) && $params !== []
            ? ' params="' . self::escapeDirectiveAttr((string) json_encode($params, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)) . '"'
            : '';
        return '::component{name="' . self::escapeDirectiveAttr($type) . '"' . $json . "}\n::";
    }

    /**
     * @param array<int, mixed> $nodes
     */
    private static function inline(array $nodes): string
    {
        $out = '';
        foreach ($nodes as $node) {
            if (!is_array($node)) {
                continue;
            }
            $type = (string) ($node['type'] ?? '');
            if ($type === 'text') {
                $text = self::escapeText((string) ($node['text'] ?? ''));
                foreach (array_reverse($node['marks'] ?? []) as $mark) {
                    if (is_array($mark)) {
                        $text = self::mark($mark, $text);
                    }
                }
                $out .= $text;
                continue;
            }
            if ($type === 'hardBreak') {
                $out .= "  \n";
                continue;
            }
            $out .= self::escapeText(self::textContent($node));
        }
        return trim($out);
    }

    /**
     * @param array<string, mixed> $mark
     */
    private static function mark(array $mark, string $text): string
    {
        $attrs = $mark['attrs'] ?? [];
        return match ($mark['type'] ?? '') {
            'bold', 'strong' => '**' . $text . '**',
            'italic', 'em'   => '_' . $text . '_',
            'strike'         => '~~' . $text . '~~',
            'code'           => '`' . str_replace('`', '\`', $text) . '`',
            'link'           => self::linkMark($attrs, $text),
            default          => $text,
        };
    }

    /**
     * @param array<string, mixed> $attrs
     */
    private static function linkMark(array $attrs, string $text): string
    {
        $href = (string) ($attrs['href'] ?? '');
        if ($href === '' || preg_match('/^\s*(javascript|data|vbscript):/i', $href)) {
            return $text;
        }
        return '[' . $text . '](' . self::escapeUrl($href) . ')';
    }

    /**
     * @param array<string, mixed> $node
     */
    private static function textContent(array $node): string
    {
        if (isset($node['text'])) {
            return (string) $node['text'];
        }
        $text = '';
        foreach (($node['content'] ?? []) as $child) {
            if (is_array($child)) {
                $text .= self::textContent($child);
            }
        }
        return $text;
    }

    private static function fenceFor(string $code): string
    {
        preg_match_all('/`+/', $code, $matches);
        $max = 2;
        foreach ($matches[0] ?? [] as $match) {
            $max = max($max, strlen($match));
        }
        return str_repeat('`', $max + 1);
    }

    private static function escapeText(string $text): string
    {
        return strtr($text, [
            '\\' => '\\\\',
            '*'  => '\\*',
            '_'  => '\\_',
            '`'  => '\\`',
            '['  => '\\[',
            ']'  => '\\]',
        ]);
    }

    private static function escapeLinkText(string $text): string
    {
        return strtr($text, [
            '\\' => '\\\\',
            '['  => '\\[',
            ']'  => '\\]',
        ]);
    }

    private static function escapeUrl(string $url): string
    {
        return str_replace([' ', ')'], ['%20', '\)'], $url);
    }

    private static function escapeDirectiveAttr(string $value): string
    {
        return str_replace(['\\', '"', "\n", "\r"], ['\\\\', '\"', ' ', ' '], $value);
    }
}
