<?php
declare(strict_types=1);

/**
 * The release version, defined here because helpers.php is on Composer's
 * `files` autoload and therefore loaded by every entry point — web, CLI and
 * tests alike.
 *
 * It used to be a literal repeated in each front controller, which meant CLI
 * scripts saw no version at all: PluginLoader read 0.0.0 and silently skipped
 * every plugin declaring a `min_core_version`. Bumping a release should touch
 * exactly one line.
 */
if (!defined('TYPEDOCK_VERSION')) {
    define('TYPEDOCK_VERSION', '1.0.0-rc6');
}

// CLI entry points in the shared-hosting package execute from typedock/ while
// web assets live in the sibling public_html/. Web entry points define this
// constant themselves; CLI can safely infer it because the source checkout
// always has TYPEDOCK_ROOT/public.
if (defined('TYPEDOCK_ROOT') && !defined('TYPEDOCK_PUBLIC_DIR')) {
    $configuredPublicDir = getenv('TYPEDOCK_PUBLIC_DIR');
    $sourcePublicDir = TYPEDOCK_ROOT . '/public';
    $splitPublicDir = dirname(TYPEDOCK_ROOT) . '/public_html';
    if (is_string($configuredPublicDir) && $configuredPublicDir !== '') {
        define('TYPEDOCK_PUBLIC_DIR', rtrim($configuredPublicDir, '/\\'));
    } elseif (!is_dir($sourcePublicDir) && is_dir($splitPublicDir)) {
        define('TYPEDOCK_PUBLIC_DIR', $splitPublicDir);
    }
}

if (!function_exists('typedock_uuid7')) {
    /**
     * Generate a time-sortable UUIDv7 without a runtime package dependency.
     *
     * The 12-bit sequence makes IDs generated by this PHP process monotonic
     * within the same millisecond. The remaining 62 random bits keep IDs from
     * independent processes collision-resistant.
     */
    function typedock_uuid7(): string
    {
        static $lastMilliseconds = -1;
        static $sequence = 0;

        $milliseconds = (int) floor(microtime(true) * 1000);
        if ($milliseconds > $lastMilliseconds) {
            $lastMilliseconds = $milliseconds;
            $sequence = 0;
        } else {
            $sequence++;
            if ($sequence > 0x0fff) {
                $lastMilliseconds++;
                $sequence = 0;
            }
            $milliseconds = $lastMilliseconds;
        }

        $time = str_pad(dechex($milliseconds), 12, '0', STR_PAD_LEFT);
        $random = random_bytes(8);
        $random[0] = chr((ord($random[0]) & 0x3f) | 0x80);
        $tail = bin2hex($random);

        return substr($time, 0, 8)
            . '-' . substr($time, 8, 4)
            . '-7' . sprintf('%03x', $sequence)
            . '-' . substr($tail, 0, 4)
            . '-' . substr($tail, 4);
    }
}

if (!function_exists('typedock_load_config')) {
    /**
     * Load TypeDock's central config.php and populate $_ENV.
     *
     * Real environment variables take precedence over values in config.php,
     * so the same file works for both shared-hosting (direct values) and
     * container/PaaS deploys (injected env vars).
     */
    function typedock_load_config(string $root): bool
    {
        $path = $root . '/config.php';
        if (is_file($path)) {
            $values = require $path;
            if (is_array($values)) {
                foreach ($values as $k => $v) {
                    if (!is_string($k)) {
                        continue;
                    }
                    // Real environment variables always win over config.php.
                    $real = getenv($k);
                    if ($real !== false && $real !== '') {
                        $_ENV[$k] = $real;
                        continue;
                    }
                    $str = is_bool($v) ? ($v ? 'true' : 'false') : (string) $v;
                    if ($str === '') {
                        continue;
                    }
                    $_ENV[$k] = $str;
                    putenv("{$k}={$str}");
                }
            }
            return true;
        }

        // No config.php — configuration may still be provided entirely via
        // environment variables (docker-compose, Kubernetes, systemd, etc.).
        return getenv('DB_DRIVER') !== false;
    }
}

if (!function_exists('env')) {
    /**
     * Get environment variable value with fallback.
     */
    function env(string $key, mixed $default = null): mixed
    {
        $value = $_ENV[$key] ?? getenv($key);
        if ($value === false) {
            return $default;
        }
        return match (strtolower((string) $value)) {
            'true', '(true)'   => true,
            'false', '(false)' => false,
            'null', '(null)'   => null,
            'empty', '(empty)' => '',
            default            => $value,
        };
    }
}

if (!function_exists('config')) {
    /**
     * Get configuration value using dot notation (e.g., 'database.host').
     */
    function config(string $key, mixed $default = null): mixed
    {
        static $cache = [];

        [$file, $rest] = array_pad(explode('.', $key, 2), 2, null);

        if (!isset($cache[$file])) {
            $path = TYPEDOCK_ROOT . '/config/' . $file . '.php';
            if (!file_exists($path)) {
                return $default;
            }
            $cache[$file] = require $path;
        }

        if ($rest === null) {
            return $cache[$file] ?? $default;
        }

        $parts = explode('.', $rest);
        $value = $cache[$file];
        foreach ($parts as $part) {
            if (!is_array($value) || !array_key_exists($part, $value)) {
                return $default;
            }
            $value = $value[$part];
        }

        return $value;
    }
}

if (!function_exists('__')) {
    function __(string $original, mixed ...$params): string
    {
        try {
            return \Flight::translator()->translate($original, ...$params);
        } catch (\Throwable) {
            if ($params === []) {
                return $original;
            }
            $values = count($params) === 1 && is_array($params[0] ?? null) ? $params[0] : $params;
            $replace = [];
            foreach ($values as $key => $value) {
                if (is_scalar($value) || $value === null) {
                    $replace['{' . (string) $key . '}'] = (string) $value;
                }
            }
            return $replace === [] ? $original : strtr($original, $replace);
        }
    }
}

if (!function_exists('base_path')) {
    function base_path(string $path = ''): string
    {
        return TYPEDOCK_ROOT . ($path !== '' ? DIRECTORY_SEPARATOR . ltrim($path, DIRECTORY_SEPARATOR) : '');
    }
}

if (!function_exists('storage_path')) {
    function storage_path(string $path = ''): string
    {
        return TYPEDOCK_ROOT . '/storage' . ($path !== '' ? DIRECTORY_SEPARATOR . ltrim($path, DIRECTORY_SEPARATOR) : '');
    }
}

if (!function_exists('public_path')) {
    /**
     * Filesystem path to the web-accessible directory.
     *
     * Defaults to TYPEDOCK_ROOT/public (standard source layout). The shared-hosting
     * distribution ships with `public_html/` and `typedock/` as sibling folders and
     * sets TYPEDOCK_PUBLIC_DIR at the entry point so asset publishing and uploads
     * target the correct directory.
     */
    function public_path(string $path = ''): string
    {
        $base = defined('TYPEDOCK_PUBLIC_DIR') ? TYPEDOCK_PUBLIC_DIR : TYPEDOCK_ROOT . '/public';
        return $base . ($path !== '' ? DIRECTORY_SEPARATOR . ltrim($path, DIRECTORY_SEPARATOR) : '');
    }
}

if (!function_exists('typedock_is_https')) {
    /**
     * True when the current request is being served over HTTPS, including
     * the case where TLS is terminated at an upstream proxy (Cloudflare,
     * nginx, etc.) and forwarded as plain HTTP via `X-Forwarded-Proto`.
     */
    function typedock_is_https(): bool
    {
        $https = $_SERVER['HTTPS'] ?? '';
        if ($https !== '' && strtolower((string) $https) !== 'off') {
            return true;
        }
        if (((int) ($_SERVER['SERVER_PORT'] ?? 0)) === 443) {
            return true;
        }
        if (strtolower((string) ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '')) === 'https') {
            return true;
        }
        return false;
    }
}

if (!function_exists('typedock_session_cookie_name')) {
    /**
     * Name of the PHP session cookie. A TypeDock-specific name (rather than
     * the default PHPSESSID) lets operators write a single "bypass the cache
     * when this cookie is present" rule at the CDN. Override with the
     * SESSION_NAME env var; invalid names fall back to the default because
     * PHP only accepts alphanumerics here.
     */
    function typedock_session_cookie_name(): string
    {
        $name = (string) ($_ENV['SESSION_NAME'] ?? getenv('SESSION_NAME') ?: '');

        if ($name === '' || ctype_digit($name) || preg_match('/^[A-Za-z0-9_]{1,64}$/', $name) !== 1) {
            return 'typedock_session';
        }

        return $name;
    }
}

if (!function_exists('typedock_configure_session_cookie')) {
    /**
     * Apply hardened session cookie defaults at runtime. Called once from
     * public/index.php before any session_start() so the entire app inherits
     * these params — important for shared-hosting deploys where editing
     * php.ini isn't an option.
     *
     *   - HttpOnly: blocks JS access to the session cookie (XSS mitigation).
     *   - SameSite=Lax: blocks cross-site POSTs while allowing top-level GET
     *     navigation (works with admin login redirect chains).
     *   - Secure: only over real HTTPS, including TLS-terminating proxies.
     *
     * Also pins PHP's session cache limiter to `nocache`. That is already the
     * stock default, but it is a php.ini setting a shared host can change —
     * `session.cache_limiter = public` would have PHP stamp
     * `Cache-Control: public, max-age=...` on admin responses. Pinning it
     * removes that variable, and keeps PHP's automatic downgrade as a
     * backstop for any code that opens a session without going through
     * typedock_session_start(). CacheHeadersMiddleware still has the final
     * word: it runs after session_start() and replaces the header with its
     * own value.
     *
     * Idempotent — safe to call multiple times. No-op if a session has
     * already been started (PHP cannot change the params after that point).
     */
    function typedock_configure_session_cookie(): void
    {
        if (session_status() !== PHP_SESSION_NONE) {
            return;
        }

        session_name(typedock_session_cookie_name());
        session_cache_limiter('nocache');

        $lifetime = (int) ($_ENV['SESSION_LIFETIME'] ?? getenv('SESSION_LIFETIME') ?: 0);
        if ($lifetime < 0) {
            $lifetime = 0;
        }

        session_set_cookie_params([
            'lifetime' => $lifetime,
            'path'     => '/',
            'domain'   => '',
            'secure'   => typedock_is_https(),
            'httponly' => true,
            'samesite' => 'Lax',
        ]);
    }
}

if (!function_exists('typedock_session_start')) {
    /**
     * Start (or adopt) the PHP session and mark the response uncacheable.
     *
     * Every session_start() in TypeDock goes through here so the invariant
     * holds structurally: a response that can carry per-visitor state — a
     * CSRF token, a flash message, an admin screen — is never offered to a
     * shared cache, whichever code path opened the session.
     */
    function typedock_session_start(): bool
    {
        $started = true;

        if (session_status() === PHP_SESSION_NONE) {
            typedock_configure_session_cookie();
            $started = session_start();
        }

        \TypeDock\Middleware\CacheHeadersMiddleware::markPrivate();

        return $started;
    }
}

if (!function_exists('site_option')) {
    /**
     * Read a site_options row, decoded from JSON. Cached for the lifetime of
     * the request so the Router, breadcrumb builder, SEO service, etc. can
     * all call this freely without producing N trips to the DB.
     *
     * On any failure (DB down, table missing during install, option unset)
     * the supplied $default is returned — callers never have to handle an
     * exception here.
     */
    function site_option(string $key, mixed $default = null): mixed
    {
        static $cache = null;
        if ($cache === null) {
            $cache = [];
            try {
                $stmt = \Flight::db()->query('SELECT key_name, value FROM site_options');
                foreach ($stmt->fetchAll() as $row) {
                    $cache[(string) $row['key_name']] = json_decode((string) $row['value'], true);
                }
            } catch (\Throwable) {
                // Leave $cache empty; callers fall through to $default.
            }
        }
        $val = $cache[$key] ?? null;
        return $val !== null && $val !== '' ? $val : $default;
    }
}

if (!function_exists('typedock_default_locale')) {
    /**
     * Canonical locale for single-locale public content. Falls back safely
     * during install/migration before Flight services or the locales table
     * are available.
     */
    function typedock_default_locale(): string
    {
        try {
            $locale = (string) \Flight::locales()->defaultLocale();
        } catch (\Throwable) {
            $locale = (string) config('app.locale', 'en');
        }

        $locale = strtolower(trim($locale));
        return $locale !== '' ? $locale : 'en';
    }
}

if (!function_exists('typedock_current_locale')) {
    /**
     * Current request locale when locale routing is enabled, otherwise the
     * site default locale. Admin UI language is intentionally separate.
     */
    function typedock_current_locale(): string
    {
        try {
            $locale = (string) \Flight::locales()->current();
        } catch (\Throwable) {
            $locale = typedock_default_locale();
        }

        $locale = strtolower(trim($locale));
        return $locale !== '' ? $locale : typedock_default_locale();
    }
}

if (!function_exists('posts_archive_slug')) {
    /**
     * The URL path segment used for the posts archive + single posts.
     * Defaults to `blog`; operators can override via Settings → General.
     */
    function posts_archive_slug(): string
    {
        $slug = (string) site_option('site.posts_archive_slug', 'blog');
        return trim($slug, '/') !== '' ? trim($slug, '/') : 'blog';
    }
}

if (!function_exists('post_path')) {
    /**
     * Build a root-relative URL for a post slug, honouring the configured
     * posts_archive_slug. Example: post_path('hello') → '/blog/hello'.
     * When $slug is empty, returns the archive path itself.
     */
    function post_path(string $slug = ''): string
    {
        $prefix = '/' . posts_archive_slug();
        return $slug === '' ? $prefix : $prefix . '/' . ltrim($slug, '/');
    }
}
